version: '3.1'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - default-net
    command: mongod --smallfiles --logpath=/dev/null --quiet

  app:
    container_name: trackingfriendsservice
    restart: always
    build: .
    ports:
      - 8080:8080
    networks:
      - default-net
    depends_on:
      - mongodb
    links:
      - mongodb

networks:
  default-net: